// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace VLivingAPI.Repositories.Data.Models;

public partial class VLivingDbContext : DbContext
{
    public VLivingDbContext()
    {
    }

    public VLivingDbContext(DbContextOptions<VLivingDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Activity> Activities { get; set; }

    public virtual DbSet<Ad> Ads { get; set; }

    public virtual DbSet<AdRequest> AdRequests { get; set; }

    public virtual DbSet<Amenity> Amenities { get; set; }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<EmailVerificationToken> EmailVerificationTokens { get; set; }

    public virtual DbSet<Location> Locations { get; set; }

    public virtual DbSet<Message> Messages { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<PasswordResetToken> PasswordResetTokens { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Post> Posts { get; set; }

    public virtual DbSet<PostAmenity> PostAmenities { get; set; }

    public virtual DbSet<PostReview> PostReviews { get; set; }

    public virtual DbSet<PostType> PostTypes { get; set; }

    public virtual DbSet<PropertyForm> PropertyForms { get; set; }

    public virtual DbSet<PropertyType> PropertyTypes { get; set; }

    public virtual DbSet<RefreshToken> RefreshTokens { get; set; }

    public virtual DbSet<RoommateMatch> RoommateMatches { get; set; }

    public virtual DbSet<RoommatePreference> RoommatePreferences { get; set; }

    public virtual DbSet<SubscriptionPlan> SubscriptionPlans { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserSubscription> UserSubscriptions { get; set; }
    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
    //    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
    //        => optionsBuilder.UseSqlServer("Data Source=localhost;Initial Catalog=VLivingDb;Persist Security Info=True;User ID=sa;Password=YourStrongPass123!;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Activity>(entity =>
        {
            entity.HasKey(e => e.ActivityId).HasName("PK__Activiti__45F4A7F13670F0BE");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Status).HasDefaultValue("active");

            entity.HasOne(d => d.Creator).WithMany(p => p.Activities)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Activitie__Creat__7BB05806");

            entity.HasOne(d => d.Location).WithMany(p => p.Activities).HasConstraintName("FK__Activitie__Locat__7CA47C3F");
        });

        modelBuilder.Entity<Ad>(entity =>
        {
            entity.HasKey(e => e.AdId).HasName("PK__Ads__7130D58E64C0F4D5");

            entity.Property(e => e.Clicks).HasDefaultValue(0);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Status).HasDefaultValue("active");
            entity.Property(e => e.Views).HasDefaultValue(0);

            entity.HasOne(d => d.Request).WithMany(p => p.Ads)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Ads__RequestID__24B26D99");

            entity.HasOne(d => d.User).WithMany(p => p.Ads)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Ads__UserID__25A691D2");
        });

        modelBuilder.Entity<AdRequest>(entity =>
        {
            entity.HasKey(e => e.RequestId).HasName("PK__AdReques__33A8519ACDFB1035");

            entity.ToTable(tb => tb.HasTrigger("TR_AdRequest_Approve"));

            entity.Property(e => e.Status).HasDefaultValue("pending");
            entity.Property(e => e.SubmittedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.User).WithMany(p => p.AdRequests)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__AdRequest__UserI__1E05700A");
        });

        modelBuilder.Entity<Amenity>(entity =>
        {
            entity.HasKey(e => e.AmenityId).HasName("PK__Amenitie__842AF52B68DAA9D8");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.BookingId).HasName("PK__Bookings__73951ACD05800EBB");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Status).HasDefaultValue("pending");

            entity.HasOne(d => d.Post).WithMany(p => p.Bookings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Bookings__PostID__025D5595");

            entity.HasOne(d => d.User).WithMany(p => p.Bookings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Bookings__UserID__0169315C");
        });

        modelBuilder.Entity<EmailVerificationToken>(entity =>
        {
            entity.HasKey(e => e.TokenId).HasName("PK__EmailVer__658FEE8A9616A9AC");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsUsed).HasDefaultValue(false);

            entity.HasOne(d => d.User).WithMany(p => p.EmailVerificationTokens).HasConstraintName("FK__EmailVeri__UserI__2B5F6B28");
        });

        modelBuilder.Entity<Location>(entity =>
        {
            entity.HasKey(e => e.LocationId).HasName("PK__Location__E7FEA477FBAAAF27");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Level).HasDefaultValue(1);

            entity.HasOne(d => d.ParentLocation).WithMany(p => p.InverseParentLocation).HasConstraintName("FK__Locations__Paren__5F141958");
        });

        modelBuilder.Entity<Message>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__Messages__C87C037C1BABCEAF");

            entity.Property(e => e.IsRead).HasDefaultValue(false);
            entity.Property(e => e.SentAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Receiver).WithMany(p => p.MessageReceivers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Messages__Receiv__08162EEB");

            entity.HasOne(d => d.Sender).WithMany(p => p.MessageSenders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Messages__Sender__07220AB2");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.NotificationId).HasName("PK__Notifica__20CF2E32D33158D3");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsRead).HasDefaultValue(false);

            entity.HasOne(d => d.User).WithMany(p => p.Notifications)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Notificat__UserI__0CDAE408");
        });

        modelBuilder.Entity<PasswordResetToken>(entity =>
        {
            entity.HasKey(e => e.TokenId).HasName("PK__Password__658FEE8A32C2CB3B");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsUsed).HasDefaultValue(false);

            entity.HasOne(d => d.User).WithMany(p => p.PasswordResetTokens).HasConstraintName("FK__PasswordR__UserI__30242045");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__Payments__9B556A581BF5BE94");

            entity.Property(e => e.Status).HasDefaultValue("pending");

            entity.HasOne(d => d.Booking).WithMany(p => p.Payments).HasConstraintName("FK__Payments__Bookin__1940BAED");

            entity.HasOne(d => d.Subscription).WithMany(p => p.Payments).HasConstraintName("FK__Payments__Subscr__184C96B4");

            entity.HasOne(d => d.User).WithMany(p => p.Payments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Payments__UserID__1758727B");
        });

        modelBuilder.Entity<Post>(entity =>
        {
            entity.HasKey(e => e.PostId).HasName("PK__Posts__AA1260384F498F68");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Status).HasDefaultValue("active");
            entity.Property(e => e.Views).HasDefaultValue(0);

            entity.HasOne(d => d.Location).WithMany(p => p.Posts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Posts__LocationI__6A85CC04");

            entity.HasOne(d => d.PostType).WithMany(p => p.Posts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Posts__PostTypeI__67A95F59");

            entity.HasOne(d => d.PropertyForm).WithMany(p => p.Posts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Posts__PropertyF__6991A7CB");

            entity.HasOne(d => d.PropertyType).WithMany(p => p.Posts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Posts__PropertyT__689D8392");

            entity.HasOne(d => d.User).WithMany(p => p.Posts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Posts__UserID__66B53B20");
        });

        modelBuilder.Entity<PostAmenity>(entity =>
        {
            entity.HasKey(e => new { e.PostId, e.AmenityId }).HasName("PK__PostAmen__0250CF6A5BC1B1B8");

            entity.HasOne(d => d.Amenity).WithMany(p => p.PostAmenities).HasConstraintName("FK__PostAmeni__Ameni__3C89F72A");

            entity.HasOne(d => d.Post).WithMany(p => p.PostAmenities).HasConstraintName("FK__PostAmeni__PostI__3B95D2F1");
        });

        modelBuilder.Entity<PostReview>(entity =>
        {
            entity.HasKey(e => e.ReviewId).HasName("PK__PostRevi__74BC79AE332732E6");

            entity.Property(e => e.IsVerified).HasDefaultValue(false);
            entity.Property(e => e.ReviewDate).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Booking).WithMany(p => p.PostReviews).HasConstraintName("FK__PostRevie__Booki__442B18F2");

            entity.HasOne(d => d.Post).WithMany(p => p.PostReviews)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PostRevie__PostI__4242D080");

            entity.HasOne(d => d.Reviewer).WithMany(p => p.PostReviews)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PostRevie__Revie__4336F4B9");
        });

        modelBuilder.Entity<PostType>(entity =>
        {
            entity.HasKey(e => e.PostTypeId).HasName("PK__PostType__AB212610CE230A57");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<PropertyForm>(entity =>
        {
            entity.HasKey(e => e.PropertyFormId).HasName("PK__Property__56B70EC31113FE2A");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<PropertyType>(entity =>
        {
            entity.HasKey(e => e.PropertyTypeId).HasName("PK__Property__BDE14DD4C2559C93");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<RefreshToken>(entity =>
        {
            entity.HasKey(e => e.RefreshTokenId).HasName("PK__RefreshT__F5845E594D9D1D1A");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsRevoked).HasDefaultValue(false);

            entity.HasOne(d => d.User).WithMany(p => p.RefreshTokens).HasConstraintName("FK__RefreshTo__UserI__34E8D562");
        });

        modelBuilder.Entity<RoommateMatch>(entity =>
        {
            entity.HasKey(e => e.MatchId).HasName("PK__Roommate__4218C837748D8D50");

            entity.Property(e => e.MatchedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Status).HasDefaultValue("pending");

            entity.HasOne(d => d.UserId1Navigation).WithMany(p => p.RoommateMatchUserId1Navigations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RoommateM__UserI__75F77EB0");

            entity.HasOne(d => d.UserId2Navigation).WithMany(p => p.RoommateMatchUserId2Navigations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RoommateM__UserI__76EBA2E9");
        });

        modelBuilder.Entity<RoommatePreference>(entity =>
        {
            entity.HasKey(e => e.PreferenceId).HasName("PK__Roommate__E228490FE6CAD0AD");

            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Location).WithMany(p => p.RoommatePreferences).HasConstraintName("FK__RoommateP__Locat__703EA55A");

            entity.HasOne(d => d.User).WithOne(p => p.RoommatePreference)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RoommateP__UserI__6F4A8121");
        });

        modelBuilder.Entity<SubscriptionPlan>(entity =>
        {
            entity.HasKey(e => e.PlanId).HasName("PK__Subscrip__755C22D7C2B220CB");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.DurationMonths).HasDefaultValue(1);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CCAC974EE360");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsAdvertiserApproved).HasDefaultValue(false);
            entity.Property(e => e.IsEmailVerified).HasDefaultValue(false);

            entity.HasOne(d => d.SubscriptionPlan).WithMany(p => p.Users).HasConstraintName("FK__Users__Subscript__595B4002");
        });

        modelBuilder.Entity<UserSubscription>(entity =>
        {
            entity.HasKey(e => e.SubscriptionId).HasName("PK__UserSubs__9A2B24BDB57C69D6");

            entity.Property(e => e.AutoRenew).HasDefaultValue(true);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Status).HasDefaultValue("active");

            entity.HasOne(d => d.Plan).WithMany(p => p.UserSubscriptions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserSubsc__PlanI__1387E197");

            entity.HasOne(d => d.User).WithMany(p => p.UserSubscriptions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserSubsc__UserI__1293BD5E");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}