// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VLivingAPI.Repositories.Data.Models;

public partial class Activity
{
    [Key]
    [Column("ActivityID")]
    public int ActivityId { get; set; }

    [Column("CreatorID")]
    public int CreatorId { get; set; }

    [StringLength(200)]
    public string Title { get; set; }

    public string Description { get; set; }

    [Column("LocationID")]
    public int? LocationId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? StartTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndTime { get; set; }

    [StringLength(20)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("CreatorId")]
    [InverseProperty("Activities")]
    public virtual User Creator { get; set; }

    [ForeignKey("LocationId")]
    [InverseProperty("Activities")]
    public virtual Location Location { get; set; }
}