// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VLivingAPI.Repositories.Data.Models;

[Index("Status", Name = "IDX_Ads_Status")]
public partial class Ad
{
    [Key]
    [Column("AdID")]
    public int AdId { get; set; }

    [Column("RequestID")]
    public int RequestId { get; set; }

    [Column("UserID")]
    public int UserId { get; set; }

    [StringLength(200)]
    public string Title { get; set; }

    public string Content { get; set; }

    [Column("ImageURL")]
    [StringLength(255)]
    public string ImageUrl { get; set; }

    [Column("LinkURL")]
    [StringLength(255)]
    public string LinkUrl { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public int? Views { get; set; }

    public int? Clicks { get; set; }

    [StringLength(20)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("RequestId")]
    [InverseProperty("Ads")]
    public virtual AdRequest Request { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Ads")]
    public virtual User User { get; set; }
}