// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VLivingAPI.Repositories.Data.Models;

[Index("Status", Name = "IDX_AdRequests_Status")]
[Index("UserId", Name = "IDX_AdRequests_UserID")]
public partial class AdRequest
{
    [Key]
    [Column("RequestID")]
    public int RequestId { get; set; }

    [Column("UserID")]
    public int UserId { get; set; }

    [StringLength(100)]
    public string CompanyName { get; set; }

    public string AdContent { get; set; }

    [StringLength(255)]
    public string TargetAudience { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Budget { get; set; }

    public int? DurationDays { get; set; }

    [StringLength(20)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SubmittedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ApprovedAt { get; set; }

    [InverseProperty("Request")]
    public virtual ICollection<Ad> Ads { get; set; } = new List<Ad>();

    [ForeignKey("UserId")]
    [InverseProperty("AdRequests")]
    public virtual User User { get; set; }
}