// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repositories.Models;

[Index("ApartmentCode", Name = "IDX_Apartments_ApartmentCode")]
[Index("BuildingId", Name = "IDX_Apartments_BuildingID")]
public partial class Apartment
{
    [Key]
    [Column("ApartmentID")]
    public int ApartmentId { get; set; }

    [Column("BuildingID")]
    public int? BuildingId { get; set; }

    [StringLength(50)]
    public string ApartmentCode { get; set; }

    public int? Floor { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Area { get; set; }

    [StringLength(50)]
    public string ApartmentType { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    public int? NumberBathroom { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("BuildingId")]
    [InverseProperty("Apartments")]
    public virtual Building Building { get; set; }

    [InverseProperty("Apartment")]
    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();
}