// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VLivingAPI.Repositories.Models;

[Table("Booking")]
[Index("PostId", Name = "IDX_Booking_PostID")]
[Index("RenterId", Name = "IDX_Booking_RenterID")]
public partial class Booking
{
    [Key]
    [Column("BookingID")]
    public int BookingId { get; set; }

    [Column("RenterID")]
    public int RenterId { get; set; }

    [Column("PostID")]
    public int PostId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? MeetingTime { get; set; }

    [StringLength(255)]
    public string PlaceMeet { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("PostId")]
    [InverseProperty("Bookings")]
    public virtual Post Post { get; set; }

    [ForeignKey("RenterId")]
    [InverseProperty("Bookings")]
    public virtual User Renter { get; set; }
}