// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repositories.Models;

[Table("Booking")]
[Index("PostId", Name = "IDX_Booking_PostID")]
[Index("RenterId", Name = "IDX_Booking_RenterID")]
public partial class Booking
{
    [Key]
    [Column("BookingID")]
    public int BookingId { get; set; }

    [Column("RenterID")]
    public int RenterId { get; set; }

    [Column("PostID")]
    public int PostId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? MeetingTime { get; set; }

    [StringLength(255)]
    public string PlaceMeet { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "decimal(10, 8)")]
    public decimal? MeetingLatitude { get; set; }

    [Column(TypeName = "decimal(11, 8)")]
    public decimal? MeetingLongitude { get; set; }

    [StringLength(500)]
    public string MeetingAddress { get; set; }

    [Column(TypeName = "decimal(8, 2)")]
    public decimal? DistanceToMeeting { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EstimatedArrivalTime { get; set; }

    public bool? IsLocationTrackingEnabled { get; set; } = false;

    [ForeignKey("PostId")]
    [InverseProperty("Bookings")]
    public virtual Post Post { get; set; }

    [ForeignKey("RenterId")]
    [InverseProperty("Bookings")]
    public virtual User Renter { get; set; }

    [InverseProperty("Booking")]
    public virtual ICollection<LocationTrackingHistory> LocationTrackingHistories { get; set; } = new List<LocationTrackingHistory>();
}