// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VLivingAPI.Repositories.Data.Models;

[Index("PostId", Name = "IDX_Bookings_PostID")]
[Index("Status", Name = "IDX_Bookings_Status")]
[Index("UserId", Name = "IDX_Bookings_UserID")]
public partial class Booking
{
    [Key]
    [Column("BookingID")]
    public int BookingId { get; set; }

    [Column("UserID")]
    public int UserId { get; set; }

    [Column("PostID")]
    public int PostId { get; set; }

    [Required]
    [StringLength(20)]
    public string Type { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Amount { get; set; }

    [StringLength(20)]
    public string Status { get; set; }

    [StringLength(50)]
    public string PaymentMethod { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [InverseProperty("Booking")]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    [ForeignKey("PostId")]
    [InverseProperty("Bookings")]
    public virtual Post Post { get; set; }

    [InverseProperty("Booking")]
    public virtual ICollection<PostReview> PostReviews { get; set; } = new List<PostReview>();

    [ForeignKey("UserId")]
    [InverseProperty("Bookings")]
    public virtual User User { get; set; }
}