// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repositories.Models;

[Index("BlockCode", Name = "IDX_Buildings_BlockCode")]
[Index("SubdivisionId", Name = "IDX_Buildings_SubdivisionID")]
public partial class Building
{
    [Key]
    [Column("BuildingID")]
    public int BuildingId { get; set; }

    [Column("SubdivisionID")]
    public int? SubdivisionId { get; set; }

    [StringLength(100)]
    public string Name { get; set; }

    [StringLength(50)]
    public string BlockCode { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [InverseProperty("Building")]
    public virtual ICollection<Apartment> Apartments { get; set; } = new List<Apartment>();

    [ForeignKey("SubdivisionId")]
    [InverseProperty("Buildings")]
    public virtual Subdivision Subdivision { get; set; }
}