// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repositories.Models;

[Table("LocationTrackingHistory")]
public partial class LocationTrackingHistory
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();
    
    public int BookingId { get; set; }
    public int UserId { get; set; }
    
    [Column(TypeName = "decimal(10, 8)")]
    public decimal Latitude { get; set; }
    
    [Column(TypeName = "decimal(11, 8)")]
    public decimal Longitude { get; set; }
    
    [Column(TypeName = "decimal(8, 2)")]
    public decimal? DistanceToDestination { get; set; }
    
    [Column(TypeName = "decimal(5, 2)")]
    public decimal? Speed { get; set; }
    
    [Column(TypeName = "datetime")]
    public DateTime Timestamp { get; set; } = DateTime.UtcNow;
    
    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; } = DateTime.UtcNow;

    [ForeignKey(nameof(BookingId))]
    [InverseProperty("LocationTrackingHistories")]
    public virtual Booking Booking { get; set; }
    
    [ForeignKey(nameof(UserId))]
    [InverseProperty("LocationTrackingHistories")]
    public virtual User User { get; set; }
}