// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VLivingAPI.Repositories.Data.Models;

[Index("Name", Name = "IDX_Locations_Name")]
public partial class Location
{
    [Key]
    [Column("LocationID")]
    public int LocationId { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    [Column("ParentLocationID")]
    public int? ParentLocationId { get; set; }

    [InverseProperty("Location")]
    public virtual ICollection<Activity> Activities { get; set; } = new List<Activity>();

    [InverseProperty("ParentLocation")]
    public virtual ICollection<Location> InverseParentLocation { get; set; } = new List<Location>();

    [ForeignKey("ParentLocationId")]
    [InverseProperty("InverseParentLocation")]
    public virtual Location ParentLocation { get; set; }

    [InverseProperty("Location")]
    public virtual ICollection<Property> Properties { get; set; } = new List<Property>();

    [InverseProperty("Location")]
    public virtual ICollection<RoommatePreference> RoommatePreferences { get; set; } = new List<RoommatePreference>();
}