// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VLivingAPI.Repositories.Data.Models;

[Index("SenderId", "ReceiverId", Name = "IDX_Messages_SenderReceiver")]
public partial class Message
{
    [Key]
    [Column("MessageID")]
    public int MessageId { get; set; }

    [Column("SenderID")]
    public int SenderId { get; set; }

    [Column("ReceiverID")]
    public int ReceiverId { get; set; }

    public string Content { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SentAt { get; set; }

    public bool? IsRead { get; set; }

    [ForeignKey("ReceiverId")]
    [InverseProperty("MessageReceivers")]
    public virtual User Receiver { get; set; }

    [ForeignKey("SenderId")]
    [InverseProperty("MessageSenders")]
    public virtual User Sender { get; set; }
}