// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repositories.Models;

[Index("Status", Name = "IDX_Payments_Status")]
[Index("UserId", Name = "IDX_Payments_UserID")]
public partial class Payment
{
    [Key]
    [Column("PaymentID")]
    public int PaymentId { get; set; }

    [Column("UserID")]
    public int UserId { get; set; }

    [Column("UserSubID")]
    public int? UserSubId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Amount { get; set; }

    [StringLength(50)]
    public string PaymentMethod { get; set; }

    [StringLength(20)]
    public string Status { get; set; }

    [Column("TransactionID")]
    [StringLength(100)]
    public string TransactionId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PaidAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Payments")]
    public virtual User User { get; set; }

    [ForeignKey("UserSubId")]
    [InverseProperty("Payments")]
    public virtual UserSubscription UserSub { get; set; }
}