// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VLivingAPI.Repositories.Data.Models;

[Index("CreatedAt", Name = "IDX_Posts_CreatedAt")]
[Index("Type", Name = "IDX_Posts_Type")]
public partial class Post
{
    [Key]
    [Column("PostID")]
    public int PostId { get; set; }

    [Column("UserID")]
    public int UserId { get; set; }

    [Column("PropertyID")]
    public int? PropertyId { get; set; }

    [Required]
    [StringLength(20)]
    public string Type { get; set; }

    [Required]
    [StringLength(200)]
    public string Title { get; set; }

    public string Content { get; set; }

    public string Images { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    public int? Views { get; set; }

    [InverseProperty("Post")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [ForeignKey("PropertyId")]
    [InverseProperty("Posts")]
    public virtual Property Property { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Posts")]
    public virtual User User { get; set; }
}