// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VLivingAPI.Repositories.Models;

[PrimaryKey("PostId", "UtilityId")]
[Table("PostUtility")]
[Index("PostId", Name = "IDX_PostUtility_PostID")]
[Index("UtilityId", Name = "IDX_PostUtility_UtilityID")]
public partial class PostUtility
{
    [Key]
    [Column("PostID")]
    public int PostId { get; set; }

    [Key]
    [Column("UtilityID")]
    public int UtilityId { get; set; }

    [StringLength(255)]
    public string Notes { get; set; }

    [ForeignKey("PostId")]
    [InverseProperty("PostUtilities")]
    public virtual Post Post { get; set; }

    [ForeignKey("UtilityId")]
    [InverseProperty("PostUtilities")]
    public virtual Utility Utility { get; set; }
}