// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VLivingAPI.Repositories.Data.Models;

[PrimaryKey("PostId", "AmenityId")]
[Index("AmenityId", Name = "IDX_PostAmenities_AmenityID")]
[Index("PostId", Name = "IDX_PostAmenities_PostID")]
public partial class PostAmenity
{
    [Key]
    [Column("PostID")]
    public int PostId { get; set; }

    [Key]
    [Column("AmenityID")]
    public int AmenityId { get; set; }

    [StringLength(255)]
    public string Notes { get; set; }

    [ForeignKey("AmenityId")]
    [InverseProperty("PostAmenities")]
    public virtual Amenity Amenity { get; set; }

    [ForeignKey("PostId")]
    [InverseProperty("PostAmenities")]
    public virtual Post Post { get; set; }
}