// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VLivingAPI.Repositories.Data.Models;

[Index("PostId", Name = "IDX_PostReviews_PostID")]
[Index("Rating", Name = "IDX_PostReviews_Rating")]
[Index("ReviewDate", Name = "IDX_PostReviews_ReviewDate")]
[Index("ReviewerId", Name = "IDX_PostReviews_ReviewerID")]
public partial class PostReview
{
    [Key]
    [Column("ReviewID")]
    public int ReviewId { get; set; }

    [Column("PostID")]
    public int PostId { get; set; }

    [Column("ReviewerID")]
    public int ReviewerId { get; set; }

    [Column("BookingID")]
    public int? BookingId { get; set; }

    public int Rating { get; set; }

    public string ReviewText { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ReviewDate { get; set; }

    public bool? IsVerified { get; set; }

    [ForeignKey("BookingId")]
    [InverseProperty("PostReviews")]
    public virtual Booking Booking { get; set; }

    [ForeignKey("PostId")]
    [InverseProperty("PostReviews")]
    public virtual Post Post { get; set; }

    [ForeignKey("ReviewerId")]
    [InverseProperty("PostReviews")]
    public virtual User Reviewer { get; set; }
}