// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repositories.Models;

[Index("IsPrimary", Name = "IDX_PostImages_IsPrimary")]
[Index("PostId", Name = "IDX_PostImages_PostID")]
public partial class PostImage
{
    [Key]
    [Column("ImageID")]
    public int ImageId { get; set; }

    [Column("PostID")]
    public int PostId { get; set; }

    [Required]
    [StringLength(500)]
    [Column("ImageURL")]
    public string ImageUrl { get; set; }

    public int? DisplayOrder { get; set; }

    public bool? IsPrimary { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("PostId")]
    [InverseProperty("PostImages")]
    public virtual Post Post { get; set; }
}
