// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VLivingAPI.Repositories.Models;

[Index("ApartmentId", Name = "IDX_Posts_ApartmentID")]
[Index("Status", Name = "IDX_Posts_Status")]
[Index("UserId", Name = "IDX_Posts_UserID")]
public partial class Post
{
    [Key]
    [Column("PostID")]
    public int PostId { get; set; }

    [Column("UserID")]
    public int UserId { get; set; }

    [Column("ApartmentID")]
    public int? ApartmentId { get; set; }

    [Required]
    [StringLength(200)]
    public string Title { get; set; }

    public string Description { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Price { get; set; }

    [StringLength(50)]
    public string PostType { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("ApartmentId")]
    [InverseProperty("Posts")]
    public virtual Apartment Apartment { get; set; }

    [InverseProperty("Post")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [InverseProperty("Post")]
    public virtual ICollection<PostUtility> PostUtilities { get; set; } = new List<PostUtility>();

    [ForeignKey("UserId")]
    [InverseProperty("Posts")]
    public virtual User User { get; set; }
}