// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VLivingAPI.Repositories.Data.Models;

[Index("Name", Name = "IDX_PropertyForms_Name")]
[Index("Name", Name = "UQ__Property__737584F670B8E38D", IsUnique = true)]
public partial class PropertyForm
{
    [Key]
    [Column("PropertyFormID")]
    public int PropertyFormId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [InverseProperty("PropertyForm")]
    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();
}