// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VLivingAPI.Repositories.Data.Models;

[Index("LocationId", Name = "IDX_Properties_LocationID")]
[Index("Price", Name = "IDX_Properties_Price")]
[Index("Type", Name = "IDX_Properties_Type")]
public partial class Property
{
    [Key]
    [Column("PropertyID")]
    public int PropertyId { get; set; }

    [Column("OwnerID")]
    public int OwnerId { get; set; }

    [Column("LocationID")]
    public int LocationId { get; set; }

    [Required]
    [StringLength(20)]
    public string Type { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Price { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Area { get; set; }

    public int? Bedrooms { get; set; }

    public int? Bathrooms { get; set; }

    public string Description { get; set; }

    public string Images { get; set; }

    [StringLength(20)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [InverseProperty("Property")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [ForeignKey("LocationId")]
    [InverseProperty("Properties")]
    public virtual Location Location { get; set; }

    [ForeignKey("OwnerId")]
    [InverseProperty("Properties")]
    public virtual User Owner { get; set; }

    [InverseProperty("Property")]
    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();
}