// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VLivingAPI.Repositories.Data.Models;

[Index("Name", Name = "IDX_PropertyTypes_Name")]
[Index("Name", Name = "UQ__Property__737584F6A06D674B", IsUnique = true)]
public partial class PropertyType
{
    [Key]
    [Column("PropertyTypeID")]
    public int PropertyTypeId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [InverseProperty("PropertyType")]
    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();
}