// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VLivingAPI.Repositories.Models;

[Index("ExpiresAt", Name = "IDX_RefreshTokens_ExpiresAt")]
[Index("IsRevoked", Name = "IDX_RefreshTokens_IsRevoked")]
[Index("Token", Name = "IDX_RefreshTokens_Token")]
[Index("UserId", Name = "IDX_RefreshTokens_UserID")]
public partial class RefreshToken
{
    [Key]
    [Column("RefreshTokenID")]
    public int RefreshTokenId { get; set; }

    [Column("UserID")]
    public int UserId { get; set; }

    [Required]
    [StringLength(500)]
    public string Token { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ExpiresAt { get; set; }

    public bool? IsRevoked { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RevokedAt { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("RefreshTokens")]
    public virtual User User { get; set; }
}