// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repositories.Models;

[Index("BookingId", Name = "UQ_Reviews_BookingID", IsUnique = true)]
[Index("PostId", Name = "IDX_Reviews_PostID")]
[Index("UserId", Name = "IDX_Reviews_UserID")]
[Index("Rating", Name = "IDX_Reviews_Rating")]
[Index("CreatedAt", Name = "IDX_Reviews_CreatedAt")]
[Index("IsDeleted", Name = "IDX_Reviews_IsDeleted")]
public partial class Review
{
    [Key]
    [Column("ReviewID")]
    public int ReviewId { get; set; }

    [Column("BookingID")]
    public int BookingId { get; set; }

    [Column("UserID")]
    public int UserId { get; set; }

    [Column("PostID")]
    public int PostId { get; set; }

    public int Rating { get; set; }

    [StringLength(500)]
    public string Description { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    public bool IsDeleted { get; set; } = false;

    [ForeignKey("BookingId")]
    [InverseProperty("Review")]
    public virtual Booking Booking { get; set; }

    [ForeignKey("PostId")]
    [InverseProperty("Reviews")]
    public virtual Post Post { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Reviews")]
    public virtual User User { get; set; }
}