// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VLivingAPI.Repositories.Data.Models;

[Index("UserId1", "UserId2", Name = "UQ__Roommate__28476394E557F0F8", IsUnique = true)]
public partial class RoommateMatch
{
    [Key]
    [Column("MatchID")]
    public int MatchId { get; set; }

    [Column("UserID1")]
    public int UserId1 { get; set; }

    [Column("UserID2")]
    public int UserId2 { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? Score { get; set; }

    [StringLength(20)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? MatchedAt { get; set; }

    [ForeignKey("UserId1")]
    [InverseProperty("RoommateMatchUserId1Navigations")]
    public virtual User UserId1Navigation { get; set; }

    [ForeignKey("UserId2")]
    [InverseProperty("RoommateMatchUserId2Navigations")]
    public virtual User UserId2Navigation { get; set; }
}