// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VLivingAPI.Repositories.Data.Models;

[Index("UserId", Name = "UQ__Roommate__1788CCAD66D6AFB2", IsUnique = true)]
public partial class RoommatePreference
{
    [Key]
    [Column("PreferenceID")]
    public int PreferenceId { get; set; }

    [Column("UserID")]
    public int UserId { get; set; }

    [StringLength(20)]
    public string PreferredGender { get; set; }

    public int? AgeRangeMin { get; set; }

    public int? AgeRangeMax { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? BudgetMin { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? BudgetMax { get; set; }

    public string Habits { get; set; }

    public string Interests { get; set; }

    [Column("LocationID")]
    public int? LocationId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [ForeignKey("LocationId")]
    [InverseProperty("RoommatePreferences")]
    public virtual Location Location { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("RoommatePreference")]
    public virtual User User { get; set; }
}