// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repositories.Models;

[Index("Name", Name = "IDX_Subdivisions_Name")]
public partial class Subdivision
{
    [Key]
    [Column("SubdivisionID")]
    public int SubdivisionId { get; set; }

    [Required]
    [StringLength(200)]
    public string Name { get; set; }

    [StringLength(100)]
    public string Type { get; set; }

    public string Description { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [InverseProperty("Subdivision")]
    public virtual ICollection<Building> Buildings { get; set; } = new List<Building>();
}