// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VLivingAPI.Repositories.Data.Models;

[Index("Email", Name = "IDX_Users_Email")]
[Index("IsEmailVerified", Name = "IDX_Users_IsEmailVerified")]
[Index("Role", Name = "IDX_Users_Role")]
[Index("SubscriptionPlanId", Name = "IDX_Users_SubscriptionPlanID")]
[Index("Username", Name = "UQ__Users__536C85E45364CAA7", IsUnique = true)]
[Index("Email", Name = "UQ__Users__A9D105341F29CD20", IsUnique = true)]
public partial class User
{
    [Key]
    [Column("UserID")]
    public int UserId { get; set; }

    [Required]
    [StringLength(50)]
    public string Username { get; set; }

    [Required]
    [StringLength(100)]
    public string Email { get; set; }

    [Required]
    [StringLength(255)]
    public string Password { get; set; }

    [Required]
    [StringLength(20)]
    public string Role { get; set; }

    [StringLength(100)]
    public string FullName { get; set; }

    [StringLength(20)]
    public string PhoneNumber { get; set; }

    [Column("ProfilePictureURL")]
    [StringLength(255)]
    public string ProfilePictureUrl { get; set; }

    [StringLength(500)]
    public string Bio { get; set; }

    [Column("SubscriptionPlanID")]
    public int? SubscriptionPlanId { get; set; }

    public bool? IsAdvertiserApproved { get; set; }

    public bool? IsEmailVerified { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastLogin { get; set; }

    [InverseProperty("Creator")]
    public virtual ICollection<Activity> Activities { get; set; } = new List<Activity>();

    [InverseProperty("User")]
    public virtual ICollection<AdRequest> AdRequests { get; set; } = new List<AdRequest>();

    [InverseProperty("User")]
    public virtual ICollection<Ad> Ads { get; set; } = new List<Ad>();

    [InverseProperty("User")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [InverseProperty("User")]
    public virtual ICollection<EmailVerificationToken> EmailVerificationTokens { get; set; } = new List<EmailVerificationToken>();

    [InverseProperty("Receiver")]
    public virtual ICollection<Message> MessageReceivers { get; set; } = new List<Message>();

    [InverseProperty("Sender")]
    public virtual ICollection<Message> MessageSenders { get; set; } = new List<Message>();

    [InverseProperty("User")]
    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    [InverseProperty("User")]
    public virtual ICollection<PasswordResetToken> PasswordResetTokens { get; set; } = new List<PasswordResetToken>();

    [InverseProperty("User")]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    [InverseProperty("User")]
    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();

    [InverseProperty("Owner")]
    public virtual ICollection<Property> Properties { get; set; } = new List<Property>();

    [InverseProperty("User")]
    public virtual ICollection<RefreshToken> RefreshTokens { get; set; } = new List<RefreshToken>();

    [InverseProperty("UserId1Navigation")]
    public virtual ICollection<RoommateMatch> RoommateMatchUserId1Navigations { get; set; } = new List<RoommateMatch>();

    [InverseProperty("UserId2Navigation")]
    public virtual ICollection<RoommateMatch> RoommateMatchUserId2Navigations { get; set; } = new List<RoommateMatch>();

    [InverseProperty("User")]
    public virtual RoommatePreference RoommatePreference { get; set; }

    [ForeignKey("SubscriptionPlanId")]
    [InverseProperty("Users")]
    public virtual SubscriptionPlan SubscriptionPlan { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<UserSubscription> UserSubscriptions { get; set; } = new List<UserSubscription>();
}