// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VLivingAPI.Repositories.Data.Models;

[Index("Status", Name = "IDX_UserSubscriptions_Status")]
[Index("UserId", Name = "IDX_UserSubscriptions_UserID")]
public partial class UserSubscription
{
    [Key]
    [Column("SubscriptionID")]
    public int SubscriptionId { get; set; }

    [Column("UserID")]
    public int UserId { get; set; }

    [Column("PlanID")]
    public int PlanId { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    [StringLength(20)]
    public string Status { get; set; }

    public bool? AutoRenew { get; set; }

    public DateOnly? LastRenewDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [InverseProperty("Subscription")]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    [ForeignKey("PlanId")]
    [InverseProperty("UserSubscriptions")]
    public virtual SubscriptionPlan Plan { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserSubscriptions")]
    public virtual User User { get; set; }
}