// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VLivingAPI.Repositories.Models;

[Index("Email", Name = "IDX_Users_Email")]
[Index("IsEmailVerified", Name = "IDX_Users_IsEmailVerified")]
[Index("Role", Name = "IDX_Users_Role")]
[Index("SubscriptionPlanId", Name = "IDX_Users_SubscriptionPlanID")]
[Index("Username", Name = "UQ__Users__536C85E4330739A1", IsUnique = true)]
[Index("Email", Name = "UQ__Users__A9D105341799B8C1", IsUnique = true)]
public partial class User
{
    [Key]
    [Column("UserID")]
    public int UserId { get; set; }

    [Required]
    [StringLength(50)]
    public string Username { get; set; }

    [Required]
    [StringLength(100)]
    public string Email { get; set; }

    [Required]
    [StringLength(255)]
    public string Password { get; set; }

    [Required]
    [StringLength(20)]
    public string Role { get; set; }

    [StringLength(100)]
    public string FullName { get; set; }

    [StringLength(20)]
    public string PhoneNumber { get; set; }

    [Column("ProfilePictureURL")]
    [StringLength(255)]
    public string ProfilePictureUrl { get; set; }

    [StringLength(500)]
    public string Bio { get; set; }

    [Column("SubscriptionPlanID")]
    public int? SubscriptionPlanId { get; set; }

    public bool? IsEmailVerified { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastLogin { get; set; }

    [InverseProperty("Renter")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [InverseProperty("User")]
    public virtual ICollection<EmailVerificationToken> EmailVerificationTokens { get; set; } = new List<EmailVerificationToken>();

    [InverseProperty("User")]
    public virtual ICollection<PasswordResetToken> PasswordResetTokens { get; set; } = new List<PasswordResetToken>();

    [InverseProperty("User")]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    [InverseProperty("User")]
    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();

    [InverseProperty("User")]
    public virtual ICollection<RefreshToken> RefreshTokens { get; set; } = new List<RefreshToken>();

    [ForeignKey("SubscriptionPlanId")]
    [InverseProperty("Users")]
    public virtual SubscriptionPlan SubscriptionPlan { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<UserSubscription> UserSubscriptions { get; set; } = new List<UserSubscription>();
}