// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VLivingAPI.Repositories.Models;

[Index("Name", Name = "IDX_Utilities_Name")]
public partial class Utility
{
    [Key]
    [Column("UtilityID")]
    public int UtilityId { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [InverseProperty("Utility")]
    public virtual ICollection<PostUtility> PostUtilities { get; set; } = new List<PostUtility>();
}